/**
 * FAQ Cache Layer for LocalGenius
 * D1-based FAQ caching to reduce OpenAI API calls by 70%+
 */

import { ResponseFormatter } from '../utils/response-formatter.js';

export class FAQCache {
  constructor(db) {
    this.db = db;
    this.similarityThreshold = 0.75; // 75% similarity required for cache hit
  }

  /**
   * Search cache for similar question
   * @param {string} businessId - Business identifier
   * @param {string} question - Customer question
   * @returns {Promise<Object|null>} Cached FAQ if found
   */
  async search(businessId, question) {
    const startTime = Date.now();

    try {
      // Get all FAQs for this business
      const { results } = await this.db
        .prepare('SELECT * FROM faqs WHERE business_id = ? ORDER BY order_index ASC')
        .bind(businessId)
        .all();

      if (!results || results.length === 0) {
        return null;
      }

      // Find best matching FAQ
      let bestMatch = null;
      let bestSimilarity = 0;

      for (const faq of results) {
        const similarity = ResponseFormatter.similarity(question, faq.question);

        if (similarity > bestSimilarity && similarity >= this.similarityThreshold) {
          bestSimilarity = similarity;
          bestMatch = faq;
        }
      }

      if (bestMatch) {
        const responseTime = Date.now() - startTime;
        console.log(`Cache hit: ${bestSimilarity.toFixed(2)} similarity in ${responseTime}ms`);
        return {
          ...bestMatch,
          similarity: bestSimilarity,
          responseTime
        };
      }

      return null;
    } catch (error) {
      console.error('FAQ cache search error:', error);
      return null;
    }
  }

  /**
   * Get all FAQs for a business
   */
  async getAllFAQs(businessId) {
    try {
      const { results } = await this.db
        .prepare('SELECT * FROM faqs WHERE business_id = ? ORDER BY order_index ASC')
        .bind(businessId)
        .all();

      return results || [];
    } catch (error) {
      console.error('Error fetching FAQs:', error);
      return [];
    }
  }

  /**
   * Add or update FAQ
   */
  async upsertFAQ(businessId, question, answer, isAutoGenerated = false) {
    const id = crypto.randomUUID();
    const now = Math.floor(Date.now() / 1000);

    try {
      await this.db
        .prepare(`
          INSERT INTO faqs (id, business_id, question, answer, is_auto_generated, created_at, updated_at)
          VALUES (?, ?, ?, ?, ?, ?, ?)
        `)
        .bind(id, businessId, question, answer, isAutoGenerated ? 1 : 0, now, now)
        .run();

      return { id, success: true };
    } catch (error) {
      console.error('Error upserting FAQ:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Delete FAQ
   */
  async deleteFAQ(faqId) {
    try {
      await this.db
        .prepare('DELETE FROM faqs WHERE id = ?')
        .bind(faqId)
        .run();

      return { success: true };
    } catch (error) {
      console.error('Error deleting FAQ:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Update FAQ
   */
  async updateFAQ(faqId, question, answer) {
    const now = Math.floor(Date.now() / 1000);

    try {
      await this.db
        .prepare(`
          UPDATE faqs
          SET question = ?, answer = ?, updated_at = ?
          WHERE id = ?
        `)
        .bind(question, answer, now, faqId)
        .run();

      return { success: true };
    } catch (error) {
      console.error('Error updating FAQ:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Log chat interaction for analytics
   */
  async logChat(businessId, question, answer, responseTime, wasCached) {
    const id = crypto.randomUUID();
    const now = Math.floor(Date.now() / 1000);

    try {
      await this.db
        .prepare(`
          INSERT INTO chat_logs (id, business_id, question, answer, response_time_ms, was_cached, created_at)
          VALUES (?, ?, ?, ?, ?, ?, ?)
        `)
        .bind(id, businessId, question, answer, responseTime, wasCached ? 1 : 0, now)
        .run();
    } catch (error) {
      console.error('Error logging chat:', error);
    }
  }
}
