import type { ModelInfo } from "./spec.js";

/**
 * Generates the streaming index.ts worker file
 * Uses Web Streams API and Cloudflare AI binding
 */
export function generateIndexTs(model: ModelInfo): string {
  const lines: string[] = [];

  lines.push("// Auto-generated by Anvil CLI");
  lines.push("// Streaming LLM Worker - Cloudflare Workers AI");
  lines.push("");
  lines.push("export interface Env {");
  lines.push(`  ${model.bindingName}: Ai;`);
  lines.push("}");
  lines.push("");
  lines.push("export default {");
  lines.push("  async fetch(request: Request, env: Env): Promise<Response> {");
  lines.push("    const url = new URL(request.url);");
  lines.push("");
  lines.push("    // Handle CORS preflight");
  lines.push("    if (request.method === 'OPTIONS') {");
  lines.push("      return new Response(null, {");
  lines.push("        headers: {");
  lines.push("          'Access-Control-Allow-Origin': '*',");
  lines.push("          'Access-Control-Allow-Methods': 'POST, OPTIONS',");
  lines.push("          'Access-Control-Allow-Headers': 'Content-Type',");
  lines.push("        },");
  lines.push("      });");
  lines.push("    }");
  lines.push("");
  lines.push("    // Only accept POST requests");
  lines.push("    if (request.method !== 'POST') {");
  lines.push("      return new Response('Method not allowed', { status: 405 });");
  lines.push("    }");
  lines.push("");
  lines.push("    // Parse request body");
  lines.push("    let prompt: string;");
  lines.push("    try {");
  lines.push("      const body = await request.json<{ prompt?: string; messages?: Array<{role: string; content: string}> }>();");
  lines.push("      if (body.messages && body.messages.length > 0) {");
  lines.push("        prompt = body.messages[body.messages.length - 1].content;");
  lines.push("      } else if (body.prompt) {");
  lines.push("        prompt = body.prompt;");
  lines.push("      } else {");
  lines.push("        return new Response(JSON.stringify({ error: 'Missing prompt or messages' }), {");
  lines.push("          status: 400,");
  lines.push("          headers: { 'Content-Type': 'application/json' },");
  lines.push("        });");
  lines.push("      }");
  lines.push("    } catch {");
  lines.push("      return new Response(JSON.stringify({ error: 'Invalid JSON body' }), {");
  lines.push("        status: 400,");
  lines.push("        headers: { 'Content-Type': 'application/json' },");
  lines.push("      });");
  lines.push("    }");
  lines.push("");
  lines.push("    // Create streaming response using Web Streams API");
  lines.push("    const stream = new ReadableStream({");
  lines.push("      async start(controller) {");
  lines.push("        const encoder = new TextEncoder();");
  lines.push("");
  lines.push("        try {");
  lines.push(`          const response = await env.${model.bindingName}.run("${model.name}", {`);
  lines.push("            messages: [{ role: 'user', content: prompt }],");
  lines.push("            stream: true,");
  lines.push("          });");
  lines.push("");
  lines.push("          for await (const chunk of response) {");
  lines.push("            if (chunk.response) {");
  lines.push("              controller.enqueue(encoder.encode(`data: ${JSON.stringify({ content: chunk.response })}\\n\\n`));");
  lines.push("            }");
  lines.push("          }");
  lines.push("          controller.enqueue(encoder.encode('data: [DONE]\\n\\n'));");
  lines.push("          controller.close();");
  lines.push("        } catch (error) {");
  lines.push("          const errorMessage = error instanceof Error ? error.message : 'Unknown error';");
  lines.push("          controller.enqueue(encoder.encode(`data: ${JSON.stringify({ error: errorMessage })}\\n\\n`));");
  lines.push("          controller.close();");
  lines.push("        }");
  lines.push("      },");
  lines.push("    });");
  lines.push("");
  lines.push("    return new Response(stream, {");
  lines.push("      headers: {");
  lines.push("        'Content-Type': 'text/event-stream',");
  lines.push("        'Cache-Control': 'no-cache',");
  lines.push("        'Connection': 'keep-alive',");
  lines.push("        'Access-Control-Allow-Origin': '*',");
  lines.push("      },");
  lines.push("    });");
  lines.push("  },");
  lines.push("};");

  return lines.join("\n");
}

/**
 * Generates the wrangler.toml configuration file
 * Includes AI binding and rate limiting
 */
export function generateWranglerToml(model: ModelInfo): string {
  const lines: string[] = [];

  lines.push("# Auto-generated by Anvil CLI");
  lines.push("# Cloudflare Workers AI Configuration");
  lines.push("");
  lines.push('name = "my-llm-worker"');
  lines.push('main = "index.ts"');
  lines.push('compatibility_date = "2024-01-01"');
  lines.push("");
  lines.push("# AI Binding - connects to Cloudflare Workers AI");
  lines.push("[[ai]]");
  lines.push(`binding = "${model.bindingName}"`);
  lines.push("");
  lines.push("# Rate Limiting - prevents abuse");
  lines.push("[limits]");
  lines.push("cpu_ms = 10000");
  lines.push("");
  lines.push("# Environment variables");
  lines.push("[vars]");
  lines.push('ENVIRONMENT = "production"');

  return lines.join("\n");
}
